observeinc/manifests

bases/metrics/base/kustomization.yaml
bases/metrics/m/kustomization.yaml
bases/metrics/xl/kustomization.yaml

We lifted the workload definition out of the metrics base, rendering the
previous version pin meaningless. This commit moves the version pin to
be alongside the deployment and daemonset definitions respectively.

fix: pin grafana-agent

---

Makefile
scripts/mirror

It's generally useful to not have to rely on github in order to
distribute our manifest. For CI runs, it's more reliable to just point
at a static manifest hosted in S3. This commit adds a script to build
and mirror manifests to an s3 bucket.

build: add script to mirror manifests to S3

---

bases/events/noop/deployment.yaml
bases/events/noop/kustomization.yaml
bases/logs/m/fluent-bit.conf
bases/metrics/base/agent.yaml
bases/metrics/base/kustomization.yaml

For testing and development purposes, it can be useful to avoid TLS and
point at an HTTP sink.

feat: allow submitting to http

---

README.md
bases/traces/m/config.yaml
bases/traces/m/deployment.yaml
bases/traces/m/kustomization.yaml
bases/traces/m/service.yaml
examples/traces/README.md
examples/traces/extra.yaml
examples/traces/kustomization.yaml
examples/traces/namespace.yaml

Mostly clean port of our existing manifest:
- use contrib instead of otel-collector to allow experimental use of
more processors
- adjust deprecated config options

feat: add traces base

---

bases/logs/l/kustomization.yaml
bases/logs/m/kustomization.yaml
bases/logs/xl/kustomization.yaml
bases/logs/xs/kustomization.yaml

The buffer limit should be ~3-4x smaller than the allocated memory.
Undersizing a buffer limit isn't dire, but it does spam logs with
warnings that tailing is paused. This can happen alongside noisy
cronjobs in particular.

fix(logs): adjust buffer limit

---

bases/logs/m/daemonset.yaml
bases/logs/m/kustomization.yaml
bases/logs/m/serviceaccount.yaml

For completeness, associate a service account to each workload in
observe namespace.

fix: add service account for observe-logs

---

bases/logs/m/kustomization.yaml

Historically we would collect logs from /var/log by omission, but this
requires fluent-bit to be run in privileged security context. Disable by
default. If the data is required, we can always add a new kustomization layer.

fix: default node logs off

---

extras/openshift/constraints.yaml
extras/openshift/kustomization.yaml

OpenShift requires additional configuration around security contexts.
Define them in a separate manifest which can be loaded alongside our
base stack.

feat: add support for openshift

---

bases/logs/m/kustomization.yaml

Fluent-bit v1.8.13 has a bug which affects high volume ingest:
https://github.com/fluent/fluent-bit/issues/4991

fix: rollback fluent-bit to v1.8.12

---

README.md

The kustomize that ships with `kubectl` has a bit of a complicated past and might not be the version that you expect. Due to that, I usually prefer calling the kustomize build command myself and passing the manifests to `kubectl`. This PR updates the docs to provide that alternative method, if someone else has the same preference.

Add direct kustomize CLI usage instructions to README

---

bases/logs/m/daemonset.yaml
examples/openshift/README.md
examples/openshift/constraints.yaml
examples/openshift/kustomization.yaml
examples/openshift/patch-events.yaml
examples/openshift/patch-logs.yaml
extras/openshift/kustomization.yaml

We need to adjust fluent-bit securityContext in order to be able to
write tail DB to /var/log. We also need to increase kube-state-events
mem and cpu limits.

fix: move extras/openshift to examples/openshift

---

bases/traces/m/config.yaml

OTEL endpoints don't support a query string, we'll need to inject the
cluster UID as a resource attribute. There is no semantic convetion for
cluster UID, so I borrowed the format from the most similar defined key,
`k8s.cluster.name`

fix(traces): add clusterUid as resource attribute

---

bases/traces/m/daemonset.yaml

This should be sufficient to trigger the auto-discovery rules in
grafana-agent

feat: scrape otel-collector metrics

---

bases/traces/m/config.yaml

Traces may end up on any pod within the daemonset, so restricting
tagging to traces that belong to a particular node can be a limiting.
This configuration option is an optimization for larger clusters, and is
a problem we do not yet have for trace collection.

fix(traces): remove node filter for k8sattributesprocessor

---

stack/xl/kustomization.yaml

We were still referencing `m` sizing for logs and events. This predated
the new sizing limits.

fix: adjust xl limits

---

bases/metrics/base/agent.yaml

Under certain cases we collect more useful telemetry via logs than
metrics. For example, nginx-ingress generates a lot of metrics, all of
which are mostly useless once you are capable of ingesting the raw
access logs. This commit adds the ability to set a
`observeinc.com/scrape` annotation to a pod which behaves in the same
manner as `prometheus.io/scrape`, but targets observe collection
specifically.

feat(metrics): allow signalling pod should not be scraped

---

README.md
bases/events/noop/deployment.yaml
bases/logs/m/daemonset.yaml
bases/metrics/m/deployment.yaml
bases/metrics/xl/daemonset.yaml
bases/traces/m/daemonset.yaml

While it is relatively simple to override particular env variables using
kustomize, it is not very convenient if you're not well versed in the
tool. For quick adjustments that persist across updates, it can be
easier to just create a configMap of overrides rather than persist a
kustomization.yaml in a directory and then figure out how to keep track
of changes.
This change adds optional configMap overrides for each of our bases. We
allow for a specific, targeted configMap, or a global `env-overrides`
configMap. Unlike with kustomize, configuration changes won't be
automatically picked up, so a manual rollout is required.

feat: allow overriding environment variables with configMap

---

bases/logs/m/fluent-bit.conf
examples/pre-processing-logs/README.md
examples/pre-processing-logs/fluent-bit-extra.conf
examples/pre-processing-logs/kustomization.yaml
examples/pre-processing-logs/scripts/process.lua

When outputting logs, accept any tag that matches a given known prefix.
This enables the usecase where you may want to further process a subset
of logs, for example using some arbitrary lua extension:
```
[FILTER]
Name          rewrite_tag
Match         k8slogs
Rule          $containerName ${CONTAINER_FILTER_REGEX} k8slogs.preprocessing false
[FILTER]
Name            lua
Match           k8slogs.preprocessing
Protected_mode  true
script          /fluent-bit/etc/process.lua
call            cb_print
```
Without this change, you would need to write a separate output to export
the new tag `k8slogs.preprocessing`.

feat(logs): support wildcard matching in output

---

bases/logs/m/daemonset.yaml
bases/metrics/xl/daemonset.yaml
bases/traces/m/daemonset.yaml

None of our existing daemonsets are tested on windows, make sure we
don't schedule to windows nodes for now.

fix: avoid scheduling on windows nodes

---

README.md

The URL given to kustomize looks like a standard resource you might expect to load via browser, but in practice it refers to a `git clone` base. If you open the URL in a browser, you will get a 404. Add documentation pointing this out.

docs: disambiguate kustomize URL

---

README.md

This PR adds documentation on the default probabilistic sampler and how to customize it.

docs: Add default tracing sampling documentation

---

bases/logs/m/fluent-bit.conf
bases/logs/m/kustomization.yaml

It can be useful to exclude a given subset of container logs, such as namespace or containerName.

feat(logs): add FB_LOGS_GREP_EXCLUDE

---

bases/logs/m/fluent-bit.conf
bases/logs/m/kustomization.yaml
examples/proxy/deployment.yaml
examples/proxy/kustomization.yaml
examples/proxy/service.yaml
examples/proxy/serviceaccount.yaml

This adds a new base, which deploys a proxy for forwarding traffic directly to Observe. This is intended solely for legacy uses for now.

feat: add proxy example

---

bases/traces/base/kustomization.yaml
bases/traces/daemonset/kustomization.yaml
bases/traces/deployment/deployment.yaml
bases/traces/deployment/kustomization.yaml
bases/traces/l/patch.yaml
bases/traces/m/kustomization.yaml

We tend to name our controllers observe-<bla>, and make the top level naming independent of the containers that implement functionality.

fix(traces): reintroduce observe- prefix

---

README.md
bases/traces/daemonset/daemonset.yaml
bases/traces/deployment/deployment.yaml
scripts/test.sh

This will change the credentials used by the otel-collector deployment and daemonset to require the `otel-credentials` secret which should be an OBSERVE_TOKEN and OBSERVE_CUSTOMER filled with the respective Bearer token generated in the OpenTelemetry App and and Customer name as expected.
=== Test Plan ===
```
kubectl -n observe port-forward service/observe-traces 4317:4317
 01:32:50  INT ❯ echo ${OBSERVE_TOKEN?}
ds11GXA...R53azVlbGz:......mSUU8KBIz1VXDQGJ3b--euxWRf
──────────────────────────────────────────────────────────────────────────────────────────────────────────
 01:32:59 ✔ ❯ kubectl -n observe create secret generic otel-credentials \
--from-literal=OBSERVE_CUSTOMER=${OBSERVE_CUSTOMER?} \
--from-literal=OBSERVE_TOKEN=${OBSERVE_TOKEN?}
secret/otel-credentials created
kubectl …
```

fix(traces): otel-collector as a seperate credential

---

bases/traces/base/kustomization.yaml

When we introduced a new shim base (deployment, daemonset), we did not prefix them accordingly. #84 reintroduced the observe- prefix for the resulting controllers, but inadvertently double-prefixed all resources coming in from base/.
This PR fixes things by removing prefixing from base/kustomization.yaml. You can't build a usable traces stack without one of daemonset or deployment, so gate things on either of those layers.

fix(traces): remove superfluous prefixing

---

bases/metrics/m/deployment.yaml
bases/metrics/xl/daemonset.yaml

This fixes a regression introduced in beaa64f2 . The server config block was deprecated in 0.26.x, and should instead be provided via command line args. Without this setting, grafana-agent does not expose prometheus metrics over HTTP.

fix(metrics): export prom metrics from grafana-agent

---

bases/metrics/base/agent.yaml
bases/metrics/base/kustomization.yaml

Add configuration variables for limiting the number of samples and body size per scrape. This is primarily intended to protect against cardinality explosion. If a given target has an unbounded increase in the number of samples, we should try to error out rather than run into OOMs.
The configured bounds are conservative, but may still lead to false positives, such as in the case of `kube-state-metrics` running in a very large cluster. We happen to not need that data however since we collect state data separately, so we end up erring on the side of caution.

feat(metrics): protect against cardinality explosion

---

bases/logs/m/fluent-bit.conf
bases/logs/m/kustomization.yaml

Under heavy load fluentbit can run into issues when collecting logs out of symlinked directory: https://github.com/fluent/fluent-bit/issues/2110
This commit allows disabling inotify_watcher. We can switch default once we've confirmed there are no other regressions associated to the change.

feat(logs): allow disabling inotify_watcher

---

scripts/test.sh

Sometimes it's handy sending data to alternate clusters.

ci: allow setting OBSERVE_COLLECTOR_HOST

---

.github/workflows/release.yaml

Update kind node images to reflect builds for
https://github.com/kubernetes-sigs/kind/releases/tag/v0.16.0 (which is used by CI job) and https://endoflife.date/kubernetes
Sadly we can't keep coverage for very old kubernetes versions without building our own kind node images. We may choose to take that course if this becomes a problem.

ci: update kindest node images

---

bases/traces/deployment/deployment.yaml

This is for https://observe.atlassian.net/browse/OB-14844. Fixing the deployment>
Test Plan: 
```
$ KUSTOMIZE_DIR=stack/otel/l make apply
$ kubectl -n observe get deployment.apps observe-traces -o yaml
```
```yaml
template:
metadata:
creationTimestamp: null
labels:
app.kubernetes.io/instance: observe-traces
app.kubernetes.io/name: opentelemetry-collector
component: standalone-collector
observeinc.com/component: traces
spec:
containers:
- command:
- /otelcol-contrib
- --config=/etc/config/config.yaml
- --config=/etc/config/extra.yaml
- --set=service.telemetry.metrics.address=:58888
env:
- name: NODE_NAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: spec.nodeName
- name: OBSERVE_CLUSTER
valueFrom:
configMapKeyRef:
key: id
name: cluster-info
envFrom:
```

fix(traces) Update trace deployment to include environment k8s attrib

---

bases/logs/m/fluent-bit.conf
bases/logs/m/kustomization.yaml

Enabling `storage.metrics` in the `SERVICE` section exposes useful debugging info under `/api/v1/storage`.

feat: allow enabling of storage metrics

---

bases/metrics/README.md
bases/metrics/base/agent.yaml
bases/metrics/base/kustomization.yaml

This change allows users to configure a port name regex to be used for service discovery, rather than expecting metrics ports to be suffixed with `metrics`.

feat(metrics): make metrics endpoint port name matching configurable

---

bases/winlogs/m/fluentd.conf

This commit changes the authentication method from Bearer token to query parameter.
Some versions of Fluentd do not support interpolating environment variables in the `headers` map.
We could instead use basic auth, but that would require us to split the datatream token in the id (username) and the secret (password). This cannot be easily done in either the configuration file or Kubernetes.
This leaves the query parameter option as the best remaining solution. We already know string interpolation works correctly for string fields, so we can attach the token there.

fix(winlogs): pass token in query parameter

---

bases/metrics/base/agent.yaml

This PR to add clusterUid to prometheus remote_rewrite to include the tags for the prometheus metadata that is pushed to by grafana-agent.
Have tested the change in eng. 
Related JIRA - https://observe.atlassian.net/browse/CON-1717 & https://observe.atlassian.net/browse/OB-21039
https://101.observe-eng.com/workspace/41000011/dataset/event/Observation-41046423?filter-OBSERVATION_KIND=prom_md&s=3380-1hn05klz

fix: add clusteruid to prometheus endpoint

---

bases/metrics/README.md
bases/metrics/base/kustomization.yaml

This change mirrors the changes made to the `metrics` helm chart here: https://github.com/observeinc/helm-charts/commit/fe74bc582905b477505cdab740229727a55cc3f1
Fixes OB-21872
Fixes OB-21871

feat(metrics): update default cadvisor keep regex

---

bases/metrics/m/deployment.yaml
bases/metrics/m/kustomization.yaml
bases/metrics/xl/daemonset.yaml

This PR updates to the latest Grafana agent version and updates the binary name to `grafana-agent`

feat/upgrade grafana agent 0.36.1

---

bases/metrics/xl/kustomization.yaml

This fixes the missing agent upgrade in the xl stack

feat: upgrade grafana-agent to 0.36.1

---

.github/workflows/update-deps.yaml
updatecli/fluent-bit.yaml
updatecli/grafana.yaml
updatecli/otel.yaml

Introduce [update-cli](https://github.com/updatecli/updatecli) tool and configuration to create PR's to keep our dependencies current.
Sample run: https://github.com/hutchic-observe-meta/manifests/actions/runs/6177250098/job/16767990161
Sample PR: https://github.com/hutchic-observe-meta/manifests/pull/14

chore: automate updates via updatecli and gha

---

.github/workflows/update-deps.yaml

We desire the [default behavirour](https://github.com/peter-evans/create-pull-request#action-behaviour) that keeps updating an existing branch

chore: don't open new PR's keep the already open PR up to date

---

bases/traces/base/clusterrole.yaml
bases/traces/base/config.yaml
bases/traces/daemonset/daemonset.yaml
bases/traces/deployment/deployment.yaml

k8sattributes processor now natively supports extracting `k8s.cluster.uid`, so we don't need to handle this through the resource processor anymore.
Helm PR: https://github.com/observeinc/helm-charts/pull/69

fix: extract k8s.cluster.uid through k8sattributes

---

bases/metrics/README.md

```
$ kubectl restart rollout -n observe deployment observe-metrics
error: unknown command "restart" for "kubectl"
```
```
$ kubectl rollout restart -n observe deployment observe-metrics
deployment.apps/observe-metrics restarted
```

docs: fixed rollout restart instruction for deployment

---

bases/traces/base/config.yaml
bases/traces/base/kustomization.yaml

The memory limiter in `otel-collector` originally only allowed specifying absolute values (`limit_mib` and `spike_limit_mib`). They've since introduced relative values. We will still respect configs where the previous values were explicitly set.

feat(traces): use memory limiter percentages

---

bases/metrics/base/agent.yaml
bases/metrics/base/kustomization.yaml

Introduce a per-job scrape interval override and increase pod scrape interval to 60s, since it is a significant source of burstiness when collecting metrics.

feat(metrics): per job scrape interval, tweak defaults.

---

bases/traces/base/config.yaml
bases/traces/base/kustomization.yaml

Observe collection API has a limit of 4MB per observation event. We ideally don't want the data to be transmitted to the API just to get rejected. This is to truncate the values inside attributes and resource.attributes of a span in the hope that the entire observation will not exceed the limit from the API. 
One might want to drop the data at the OTel collector. But that would cause the entire record to be lost. 
Testing done:
- verified this in testbox. Specifically, used telemetrygen to generate a 6MB Span (basically a binary blob was inserted under the `attrbutes.load-0` key. Otel collector reports HTTP 413 without the fix. With the fix, it truncates the data and the Span message was seen in testbox UI.

Truncate to limit record size with best effort

---

bases/logs/m/fluent-bit.conf
bases/logs/m/kustomization.yaml

Ignore log files older than two days by default. This is configurable, but will avoid surprises when installing manifest for first time.

fix(logs): add FB_IGNORE_OLDER

---

bases/traces/base/kustomization.yaml

Increase it to 1MB per OB-27856. 1MB seems too liberal, but this is mainly to unblock some existing usage that depends on long attribute values. We will discuss what a better value to set long term separately.

Increase attribute value length limit for spans

---

README.md

If you are using the 1.0.0 release of the OpenTelemetry Observe app or newer, you should use the v2 collection endpoint which
provides a more efficient representation of trace observations in the datastream. For that you'll need to override the environment variable value `OBSERVE_COLLECTOR_OTEL_VERSION=v2` as described in README

added instructions for upgrading to /v2/otel endpoint

---

bases/metrics/base/agent.yaml

This commit fixes a bug whereby init containers would result in duplicate metrics. The following pod template would exercise this bug:
```
template:
metadata:
labels:
app: hello-world
annotations:
prometheus.io/scrape: "true"
prometheus.io/path: "/metrics"
prometheus.io/port: "9001"
spec:
initContainers:
- name: init
image: busybox
command: ['sh', '-c', 'echo "hello world"']
containers:
- name: main
image: quay.io/prometheuscommunity/avalanche:main
```
The `prometheus.io/port` creates targets for both containers in the resulting pod. We should assume any such annotations are not applicable to init containers. If scraping from an init container is desired, the manifest should be modified to use port names instead:
```
template:
metadata:
labels:
app: hello-world
spec:
initContainers:
- …
```

fix(metrics): only scrape init containers if port set

---

bases/traces/base/config.yaml
bases/traces/base/kustomization.yaml

Reintroduce the ability to use an `OBSERVE_CLUSTER` environment variable to override the existing `k8s.cluster.uid` resource attribute. This can be useful when migrating clusters.
In order for this override to take effect, the
`OTEL_OBSERVE_CLUSTER_ACTION` variable must be set to `upsert`. This is a somewhat clumsy API but it works around limitations in the ability to compose OTEL configuration in Kustomize.

feat(traces): allow OBSERVE_CLUSTER override

---

bases/traces/base/config.yaml

This was inadvertently omitted in
https://github.com/observeinc/manifests/pull/167. We should apply the same pipeline to all signals.

fix(traces): add resource processor to metrics, logs

---

bases/traces/base/config.yaml
bases/traces/base/kustomization.yaml
bases/traces/daemonset/kustomization.yaml
bases/traces/deployment/kustomization.yaml

Logging exporter was removed as of https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.111.0
Debug exporter is the replacement.

fix(traces): replace deprecated logging exporter
